Fix GitHub actions
    Homebrew is currently ignoring formulae, casks and commands from these taps because tap trust is required.
    Untap them with:
      brew untap aws/tap
    Trust specific formulae, casks and commands with:
      brew trust --formula <user>/<tap>/<formula>
      brew trust --cask <user>/<tap>/<cask>
      brew trust --command <user>/<tap>/<command>
    Whole-tap trust is broader and includes all current and future formulae,
    casks and commands from the listed taps. Trust whole taps with:
      brew trust aws/tap
    To disable trust checks:
      export HOMEBREW_NO_REQUIRE_TAP_TRUST=1
    This is not recommended and will be removed in a later release.
    For more information, see:
      https://docs.brew.sh/Tap-Trust

    ==> Fetching downloads for: nikitabobko/local-tap/aerospace-dev
    Error: Refusing to load cask nikitabobko/tap/aerospace from untrusted tap nikitabobko/tap.
    Run `brew trust --cask nikitabobko/tap/aerospace` or `brew trust nikitabobko/tap` to trust it.

I have no idea why aerospace-dev requires nikitabobko/tap tap, but fine